apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-hello-world-deployment
  labels:
    name: k8-hello-world-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8-hello-world-label
  template:
    metadata:
      labels:
        name: k8-hello-world-label
    spec:
      containers:
        - name: k8-hello-world
          image: ayan:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8090